require('dotenv').config();
const mongoose = require('mongoose');
const CourtVerdict = require('./models/CourtVerdict');
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/lawbook';

const verdicts = [
  {
    caseName: 'A.K. Gopalan v. State of Madras',
    citation: 'AIR 1950 SC 27',
    court: 'Supreme Court',
    year: 1950,
    judges: ['Kania CJ', 'Fazl Ali J', 'Patanjali Sastri J', 'Mehr Chand Mahajan J', 'Mukherjea J', 'Das J'],
    summary: 'First major case testing the scope of fundamental rights. The petitioner challenged his preventive detention under the Preventive Detention Act, 1950.',
    legalPrinciple: 'Each fundamental right is a self-contained code and must be interpreted independently. Article 21 only requires procedure established by law, not due process.',
    verdict: 'The Supreme Court upheld the Preventive Detention Act and adopted a narrow interpretation of Article 21, holding that the procedure established by law need not be fair, just, or reasonable.',
    significance: 'First major fundamental rights case. Later overruled by Maneka Gandhi (1978) which expanded Article 21 to include due process.',
    relatedSections: ['Article 19', 'Article 21', 'Article 22'],
    relatedActs: ['Constitution of India', 'Preventive Detention Act, 1950'],
    category: 'Constitutional',
    keywords: ['fundamental rights', 'personal liberty', 'preventive detention', 'Article 21', 'due process']
  },
  {
    caseName: 'State of Madras v. Champakam Dorairajan',
    citation: 'AIR 1951 SC 226',
    court: 'Supreme Court',
    year: 1951,
    judges: ['Kania CJ', 'Fazl Ali J', 'Patanjali Sastri J', 'Mehr Chand Mahajan J', 'Mukherjea J', 'Das J', 'Chandrasekhara Aiyar J'],
    summary: 'Challenged communal reservation system in Madras educational institutions as violating Article 29(2).',
    legalPrinciple: 'Fundamental Rights prevail over Directive Principles. Reservation based on caste in educational institutions violates Article 29(2).',
    verdict: 'Struck down the communal G.O. of Madras providing caste-based reservation. Led to the First Constitutional Amendment adding Article 15(4).',
    significance: 'First case where a law was struck down as unconstitutional. Led to the First Amendment (1951) which added Article 15(4) to enable reservation.',
    relatedSections: ['Article 15', 'Article 15(4)', 'Article 29(2)'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['reservation', 'caste', 'education', 'first amendment', 'Article 15']
  },
  {
    caseName: 'Shankari Prasad v. Union of India',
    citation: 'AIR 1951 SC 458',
    court: 'Supreme Court',
    year: 1951,
    judges: ['Patanjali Sastri CJ', 'Mehr Chand Mahajan J', 'Mukherjea J', 'Das J', 'Chandrasekhara Aiyar J'],
    summary: 'Challenged the First Amendment to the Constitution which curtailed the right to property.',
    legalPrinciple: 'Parliament has the power to amend any part of the Constitution, including fundamental rights, under Article 368.',
    verdict: 'Upheld Parliament\'s power to amend fundamental rights. The word "law" in Article 13(2) does not include a constitutional amendment.',
    significance: 'Established that Parliament can amend fundamental rights. Later overruled by Golaknath (1967) and then restored with limits by Kesavananda (1973).',
    relatedSections: ['Article 13', 'Article 368'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['amendment power', 'fundamental rights', 'Article 368', 'parliament']
  },
  {
    caseName: 'Golaknath v. State of Punjab',
    citation: 'AIR 1967 SC 1643',
    court: 'Supreme Court',
    year: 1967,
    judges: ['Subba Rao CJ', 'Wanchoo J', 'Hidayatullah J', 'Bachawat J', 'Ramaswami J', 'Shelat J', 'Vaidialingam J', 'Mitter J', 'Hegde J', 'Sikri J', 'Bhargava J'],
    summary: 'Challenged the 17th Amendment which added certain state laws to the 9th Schedule, preventing judicial review.',
    legalPrinciple: 'Parliament has NO power to amend fundamental rights. Constitutional amendments are "law" within the meaning of Article 13, and therefore cannot abridge fundamental rights.',
    verdict: 'By a majority of 6:5, the Supreme Court held that Parliament cannot amend fundamental rights under Article 368. Overruled Shankari Prasad and Sajjan Singh.',
    significance: 'Triggered a constitutional crisis and directly led to the 24th Amendment (1971) and Kesavananda Bharati case (1973).',
    relatedSections: ['Article 13', 'Article 368'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['amendment', 'fundamental rights', 'parliament power', 'Golaknath']
  },
  {
    caseName: 'Kesavananda Bharati v. State of Kerala',
    citation: '(1973) 4 SCC 225',
    court: 'Supreme Court',
    year: 1973,
    judges: ['Sikri CJ', 'Shelat J', 'Grover J', 'Hegde J', 'Mukherjea J', 'Jaganmohan Reddy J', 'Khanna J', 'Palekar J', 'Matthew J', 'Beg J', 'Dwivedi J', 'Chandrachud J', 'Ray J'],
    summary: 'Head of a Kerala mutt challenged the Kerala Land Reforms Act and the 29th Amendment which placed it in the 9th Schedule. Largest-ever Constitutional Bench of 13 judges.',
    legalPrinciple: 'Parliament can amend any part of the Constitution, including fundamental rights, BUT it cannot alter the basic structure of the Constitution. The basic structure includes: supremacy of the Constitution, republican and democratic form of government, secular character, separation of powers, federal character, and judicial review.',
    verdict: 'By 7:6, the Court held that Parliament can amend fundamental rights but cannot destroy the basic structure. Overruled Golaknath partially — Parliament CAN amend rights, but not if it destroys the basic structure.',
    significance: 'The most important constitutional case in Indian legal history. The Basic Structure Doctrine has protected Indian democracy from authoritarian amendments ever since.',
    relatedSections: ['Article 368', 'Article 13', 'Article 14', 'Article 21'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['basic structure', 'amendment', 'Kesavananda', 'fundamental rights', 'judicial review', 'landmark']
  },
  {
    caseName: 'Indira Nehru Gandhi v. Raj Narain',
    citation: '1975 Supp SCC 1',
    court: 'Supreme Court',
    year: 1975,
    judges: ['Ray CJ', 'Khanna J', 'Mathew J', 'Beg J', 'Chandrachud J'],
    summary: 'Challenged the 39th Amendment which sought to place the election of the PM beyond judicial review after Raj Narain won his case in Allahabad HC.',
    legalPrinciple: 'Free and fair elections are part of the basic structure. Judicial review cannot be taken away even by constitutional amendment.',
    verdict: 'Struck down clause (4) of Article 329A inserted by the 39th Amendment as it destroyed the basic structure by removing judicial review of PM\'s election.',
    significance: 'Applied the Basic Structure doctrine for the first time to strike down a constitutional amendment. Free and fair elections confirmed as basic structure.',
    relatedSections: ['Article 329A', 'Article 368'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['basic structure', 'election', 'judicial review', 'emergency', '39th amendment']
  },
  {
    caseName: 'ADM Jabalpur v. Shivkant Shukla',
    citation: 'AIR 1976 SC 1207',
    court: 'Supreme Court',
    year: 1976,
    judges: ['Ray CJ', 'Khanna J', 'Beg J', 'Chandrachud J', 'Bhagwati J'],
    summary: 'During the Emergency (1975-77), habeas corpus petitions were filed by political detainees. The government argued that during Emergency, Article 21 rights are suspended.',
    legalPrinciple: 'Majority held that during Emergency, when Article 21 is suspended, no person can approach any court for habeas corpus. Justice Khanna dissented, saying right to life cannot be suspended.',
    verdict: 'By 4:1, the majority held that during Emergency, courts cannot entertain habeas corpus petitions. Justice H.R. Khanna\'s lone dissent is celebrated as one of the greatest judicial acts of courage.',
    significance: 'Considered the darkest hour of the Indian judiciary. Justice Khanna\'s dissent led to him being superseded for CJI. Later effectively overruled by the 44th Amendment and K.S. Puttaswamy (2017).',
    relatedSections: ['Article 21', 'Article 359'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['emergency', 'habeas corpus', 'fundamental rights', 'suspension', 'Khanna dissent']
  },
  {
    caseName: 'Maneka Gandhi v. Union of India',
    citation: 'AIR 1978 SC 597',
    court: 'Supreme Court',
    year: 1978,
    judges: ['Beg CJ', 'Chandrachud J', 'Bhagwati J', 'Krishna Iyer J', 'Untwalia J', 'Fazal Ali J', 'Kailasam J'],
    summary: 'Maneka Gandhi\'s passport was impounded without giving reasons. She challenged the Passports Act procedure.',
    legalPrinciple: 'Article 21 requires that the procedure established by law must be right, just, fair, and reasonable — not arbitrary, fanciful or oppressive. Articles 14, 19, and 21 are not mutually exclusive but form a golden triangle.',
    verdict: 'The Court held that the right to travel abroad is part of personal liberty under Article 21. Any law depriving personal liberty must satisfy Article 14 (equality) and Article 19 (reasonableness).',
    significance: 'Revolutionized constitutional law by reading due process into Article 21. Effectively overruled A.K. Gopalan. Created the "golden triangle" of Articles 14, 19, 21.',
    relatedSections: ['Article 14', 'Article 19', 'Article 21'],
    relatedActs: ['Constitution of India', 'Passports Act, 1967'],
    category: 'Constitutional',
    keywords: ['due process', 'personal liberty', 'golden triangle', 'fair procedure', 'Article 21', 'Maneka Gandhi']
  },
  {
    caseName: 'Minerva Mills Ltd. v. Union of India',
    citation: 'AIR 1980 SC 1789',
    court: 'Supreme Court',
    year: 1980,
    judges: ['Chandrachud CJ', 'Bhagwati J', 'Gupta J', 'Untwalia J', 'Kailasam J'],
    summary: 'Challenged the 42nd Amendment (1976) which gave Parliament unlimited amending power and made DPSPs superior to fundamental rights.',
    legalPrinciple: 'The harmony between fundamental rights and DPSPs is a basic feature of the Constitution. Neither can be given absolute primacy over the other. Limited amending power under Article 368 is also a basic feature.',
    verdict: 'Struck down Section 55 of the 42nd Amendment (which gave unlimited amending power) and Section 4 (which gave primacy to DPSPs over Articles 14 and 19).',
    significance: 'Reinforced the Basic Structure doctrine. Established that balance between fundamental rights and DPSPs is itself a basic feature.',
    relatedSections: ['Article 31C', 'Article 368'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['basic structure', '42nd amendment', 'DPSPs', 'fundamental rights', 'balance']
  },
  {
    caseName: 'S.P. Gupta v. Union of India (First Judges Case)',
    citation: 'AIR 1982 SC 149',
    court: 'Supreme Court',
    year: 1982,
    judges: ['Chandrachud CJ', 'Bhagwati J', 'Gupta J', 'Tulzapurkar J', 'Pathak J', 'Fazal Ali J', 'Venkataramiah J'],
    summary: 'Challenged the government\'s role in appointment and transfer of judges. Also established the concept of Public Interest Litigation (PIL).',
    legalPrinciple: 'The Chief Justice of India need only be "consulted" — the executive has primacy in judicial appointments. Any public-spirited person can file PIL.',
    verdict: 'Held that "consultation" with CJI does not mean "concurrence." The executive has the final say in judicial appointments.',
    significance: 'Established PIL in India. However, the appointment holding was overruled by the Second Judges Case (1993) which gave primacy to the CJI.',
    relatedSections: ['Article 124', 'Article 217', 'Article 226'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['judges appointment', 'PIL', 'public interest litigation', 'consultation', 'CJI']
  },
  {
    caseName: 'Supreme Court Advocates-on-Record Association v. Union of India (Second Judges Case)',
    citation: '1993 Supp (6) SCC 632',
    court: 'Supreme Court',
    year: 1993,
    judges: ['Pandian J', 'Kuldip Singh J', 'Yogeshwar Dayal J', 'Ahmadi J', 'Verma J', 'Punchhi J', 'Ray J', 'Anand J', 'Bharucha J'],
    summary: 'Reconsidered the First Judges Case on the process of appointment of Supreme Court and High Court judges.',
    legalPrinciple: 'The CJI\'s opinion has primacy in judicial appointments. "Consultation" effectively means "concurrence." The CJI must consult two senior-most judges.',
    verdict: 'Overruled S.P. Gupta. The CJI\'s recommendation is binding on the government. Created the Collegium system of judicial appointments.',
    significance: 'Created the Collegium system that still governs judicial appointments. The government challenged this via NJAC (99th Amendment) which was struck down in 2015.',
    relatedSections: ['Article 124', 'Article 217'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['collegium', 'judicial appointments', 'CJI', 'concurrence', 'judges']
  },
  {
    caseName: 'S.R. Bommai v. Union of India',
    citation: '(1994) 3 SCC 1',
    court: 'Supreme Court',
    year: 1994,
    judges: ['Pandian J', 'Ahmadi J', 'Verma J', 'Yogeshwar Dayal J', 'S.C. Agrawal J', 'Bharucha J', 'B.P. Jeevan Reddy J', 'S.P. Bharucha J', 'Sawant J'],
    summary: 'Multiple state governments were dismissed under Article 356 (President\'s Rule). The dismissed governments challenged the proclamations.',
    legalPrinciple: 'Secularism is a basic feature of the Constitution. President\'s Rule under Article 356 is subject to judicial review. The presidential proclamation can be struck down if found mala fide or based on irrelevant grounds.',
    verdict: 'Held that Article 356 is justiciable. Secularism is a basic feature. Floor test is the only way to determine majority — the Governor\'s subjective assessment is not enough.',
    significance: 'Curtailed misuse of Article 356. Established secularism as basic structure. Made President\'s Rule subject to judicial review.',
    relatedSections: ['Article 356', 'Article 74', 'Article 25'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['Presidents Rule', 'secularism', 'basic structure', 'Article 356', 'floor test', 'federalism']
  },
  {
    caseName: 'Vishaka v. State of Rajasthan',
    citation: '(1997) 6 SCC 241',
    court: 'Supreme Court',
    year: 1997,
    judges: ['Verma CJ', 'Sujata Manohar J', 'B.N. Kirpal J'],
    summary: 'A social worker (Bhanwari Devi) was gang-raped for trying to prevent a child marriage. PIL filed by Vishaka and other NGOs.',
    legalPrinciple: 'In the absence of legislation, the Supreme Court can lay down guidelines having the force of law. Sexual harassment at the workplace violates Articles 14, 15, 19(1)(g), and 21.',
    verdict: 'Laid down detailed guidelines (Vishaka Guidelines) for prevention and redressal of sexual harassment at the workplace, to be followed until legislation was enacted.',
    significance: 'Led to the POSH Act, 2013. Landmark use of judicial activism to fill legislative vacuum. The guidelines operated as binding law for 16 years until POSH was enacted.',
    relatedSections: ['Article 14', 'Article 15', 'Article 19(1)(g)', 'Article 21'],
    relatedActs: ['Constitution of India', 'POSH Act, 2013'],
    category: 'Constitutional',
    keywords: ['sexual harassment', 'Vishaka', 'workplace', 'guidelines', 'women rights', 'POSH']
  },
  {
    caseName: 'L. Chandra Kumar v. Union of India',
    citation: '(1997) 3 SCC 261',
    court: 'Supreme Court',
    year: 1997,
    judges: ['Ahmadi CJ', 'Hansaria J', 'S.C. Agrawal J', 'B.P. Jeevan Reddy J', 'Suhas Patel J', 'G.B. Pattanaik J', 'S. Saghir Ahmad J'],
    summary: 'Challenged Article 323A(2)(d) which excluded jurisdiction of all courts except the Supreme Court under Article 136 in respect of service matters.',
    legalPrinciple: 'Judicial review under Articles 226/227 (High Court) and Article 32 (Supreme Court) is part of the basic structure and cannot be excluded even by constitutional amendment.',
    verdict: 'Struck down the provision excluding High Court jurisdiction. All decisions of tribunals are subject to judicial review by the High Court.',
    significance: 'Established judicial review as an inviolable basic feature. All tribunals remain subject to High Court writ jurisdiction.',
    relatedSections: ['Article 32', 'Article 226', 'Article 323A'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['judicial review', 'basic structure', 'tribunals', 'High Court', 'writ jurisdiction']
  },
  {
    caseName: 'I.R. Coelho v. State of Tamil Nadu',
    citation: '(2007) 2 SCC 1',
    court: 'Supreme Court',
    year: 2007,
    judges: ['Sabharwal CJ', 'Arijit Pasayat J', 'S.H. Kapadia J', 'B.P. Singh J', 'C.K. Thakker J', 'P.K. Balasubramanyan J', 'Altamas Kabir J', 'Dalveer Bhandari J', 'Ashok Kumar Mathur J'],
    summary: 'Whether laws placed in the 9th Schedule after Kesavananda Bharati (24.4.1973) can be challenged as violating basic structure.',
    legalPrinciple: 'Laws placed in the 9th Schedule after 24.4.1973 can be challenged if they violate the basic structure or abridge fundamental rights forming part of the basic structure.',
    verdict: 'The 9th Schedule does not provide blanket immunity. Post-1973 laws in the 9th Schedule are open to judicial review if they violate the basic structure.',
    significance: 'Removed the blanket protection of the 9th Schedule and strengthened the Basic Structure doctrine further.',
    relatedSections: ['Article 31B', 'Ninth Schedule'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['ninth schedule', 'basic structure', 'judicial review', '1973']
  },
  {
    caseName: 'M. Nagaraj v. Union of India',
    citation: '(2006) 8 SCC 212',
    court: 'Supreme Court',
    year: 2006,
    judges: ['Kapadia J', 'C.K. Thakker J', 'Balakrishnan J', 'B.P. Singh J', 'Dalveer Bhandari J'],
    summary: 'Challenged constitutional amendments enabling reservation in promotions for SC/STs.',
    legalPrinciple: 'Reservation in promotions is constitutionally valid but the state must show: (1) backwardness, (2) inadequacy of representation, and (3) overall efficiency will not be affected.',
    verdict: 'Upheld the constitutional amendments (77th, 81st, 82nd, 85th) enabling reservation in promotions but imposed conditions that data must justify the reservation.',
    significance: 'Set conditions for reservation in promotions. Later partially modified by Jarnail Singh v. Lachhmi Narain Gupta (2018).',
    relatedSections: ['Article 16(4)', 'Article 16(4A)', 'Article 16(4B)'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['reservation', 'promotions', 'SC ST', 'backwardness', 'inadequate representation']
  },
  {
    caseName: 'Ashoka Kumar Thakur v. Union of India',
    citation: '(2008) 6 SCC 1',
    court: 'Supreme Court',
    year: 2008,
    judges: ['Balakrishnan CJ', 'Thakker J', 'Pasayat J', 'Dalveer Bhandari J', 'Raveendran J'],
    summary: 'Challenged the 93rd Amendment and the Central Educational Institutions Act, 2006 providing 27% OBC reservation.',
    legalPrinciple: 'OBC reservation in educational institutions is constitutionally valid. The creamy layer must be excluded. There is no need to prove backwardness for OBCs identified by the Mandal Commission.',
    verdict: 'Upheld 27% OBC reservation in central educational institutions but mandated exclusion of creamy layer. No reservation in unaided private minority institutions.',
    significance: 'Settled the OBC reservation debate for higher education. Mandated exclusion of economically advanced OBCs (creamy layer).',
    relatedSections: ['Article 15(5)', 'Article 30'],
    relatedActs: ['Constitution of India', 'Central Educational Institutions Act, 2006'],
    category: 'Constitutional',
    keywords: ['OBC reservation', 'creamy layer', 'education', 'Mandal', '27 percent']
  },
  {
    caseName: 'Mohd. Ahmed Khan v. Shah Bano Begum',
    citation: 'AIR 1985 SC 945',
    court: 'Supreme Court',
    year: 1985,
    judges: ['Chandrachud CJ', 'Ranganath Misra J', 'D.A. Desai J', 'O. Chinnappa Reddy J', 'E.S. Venkataramiah J'],
    summary: 'A 62-year-old Muslim woman claimed maintenance from her divorced husband under Section 125 CrPC.',
    legalPrinciple: 'Section 125 CrPC applies to all women irrespective of religion. A Muslim husband\'s obligation to maintain his divorced wife is not limited to the iddat period if she cannot maintain herself.',
    verdict: 'Muslim women are entitled to maintenance under Section 125 CrPC even after the iddat period. The right to maintenance is a secular right, not governed solely by personal law.',
    significance: 'One of the most politically significant cases. Led to the Muslim Women (Protection of Rights on Divorce) Act, 1986, which was seen as overturning this judgment.',
    relatedSections: ['Section 125 CrPC'],
    relatedActs: ['Code of Criminal Procedure, 1973'],
    category: 'Constitutional',
    keywords: ['Shah Bano', 'Muslim women', 'maintenance', 'divorce', 'Section 125', 'uniform civil code']
  },
  {
    caseName: 'Aruna Ramchandra Shanbaug v. Union of India',
    citation: '(2011) 4 SCC 454',
    court: 'Supreme Court',
    year: 2011,
    judges: ['Markandey Katju J', 'Gyan Sudha Misra J'],
    summary: 'PIL seeking permission for passive euthanasia for Aruna Shanbaug who was in a vegetative state for 37 years after a brutal assault.',
    legalPrinciple: 'Passive euthanasia (withdrawal of life support) is permissible under strict guidelines. Active euthanasia remains illegal. The decision must be taken by a medical board and approved by the High Court.',
    verdict: 'Allowed passive euthanasia under guidelines but rejected the plea in this specific case as the hospital staff was willing to care for her.',
    significance: 'First recognition of passive euthanasia in India. Later expanded by Common Cause v. Union of India (2018) which allowed living wills.',
    relatedSections: ['Article 21', 'Section 309 IPC'],
    relatedActs: ['Constitution of India', 'Indian Penal Code, 1860'],
    category: 'Constitutional',
    keywords: ['euthanasia', 'right to die', 'passive euthanasia', 'vegetative state', 'Article 21']
  },
  {
    caseName: 'NALSA v. Union of India',
    citation: '(2014) 5 SCC 438',
    court: 'Supreme Court',
    year: 2014,
    judges: ['Radhakrishnan J', 'Sikri J'],
    summary: 'PIL seeking legal recognition and rights for transgender persons.',
    legalPrinciple: 'Transgender persons have the right to self-identification of their gender. They are entitled to all fundamental rights including right to equality, non-discrimination, and dignity.',
    verdict: 'Recognized transgender persons as the "third gender." Directed the government to treat them as socially and educationally backward, grant OBC reservation, and provide welfare measures.',
    significance: 'Landmark recognition of transgender rights. Led to the Transgender Persons (Protection of Rights) Act, 2019.',
    relatedSections: ['Article 14', 'Article 15', 'Article 16', 'Article 19', 'Article 21'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['transgender', 'third gender', 'NALSA', 'gender identity', 'self-identification', 'LGBTQ']
  },
  {
    caseName: 'K.S. Puttaswamy v. Union of India (Right to Privacy)',
    citation: '(2017) 10 SCC 1',
    court: 'Supreme Court',
    year: 2017,
    judges: ['Khehar CJ', 'Chelameswar J', 'Bobde J', 'Chandrachud J', 'Sapre J', 'Nariman J', 'Kaul J', 'Nazeer J', 'Abdul Nazeer J'],
    summary: 'Referred by a 3-judge bench while hearing the Aadhaar challenge — whether right to privacy is a fundamental right.',
    legalPrinciple: 'Right to Privacy is a fundamental right under Article 21 of the Constitution. It is intrinsic to life and liberty and is an inherent part of Part III of the Constitution.',
    verdict: 'Unanimously held (9:0) that right to privacy is a constitutionally protected fundamental right. Overruled M.P. Sharma (1954) and Kharak Singh (1962) which had held otherwise.',
    significance: 'The most significant expansion of fundamental rights in recent times. Impacts data protection, surveillance, Aadhaar, sexual orientation, and bodily autonomy.',
    relatedSections: ['Article 14', 'Article 19', 'Article 21'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['privacy', 'fundamental right', 'Puttaswamy', 'Aadhaar', 'data protection', 'Article 21']
  },
  {
    caseName: 'Shayara Bano v. Union of India',
    citation: '(2017) 9 SCC 1',
    court: 'Supreme Court',
    year: 2017,
    judges: ['Khehar CJ', 'Kurian Joseph J', 'Nariman J', 'Abdul Nazeer J', 'Lalit J'],
    summary: 'Challenge to the practice of instant triple talaq (talaq-e-biddat) in Muslim personal law as violating fundamental rights.',
    legalPrinciple: 'Instant triple talaq is manifestly arbitrary and violates Article 14. It is not an essential religious practice protected under Article 25.',
    verdict: 'By 3:2, struck down instant triple talaq (talaq-e-biddat) as unconstitutional. Set it aside for 6 months and directed Parliament to legislate.',
    significance: 'Led to the Muslim Women (Protection of Rights on Marriage) Act, 2019 criminalizing triple talaq. Major step for Muslim women\'s rights.',
    relatedSections: ['Article 14', 'Article 15', 'Article 21', 'Article 25'],
    relatedActs: ['Constitution of India', 'Muslim Personal Law (Shariat) Application Act, 1937'],
    category: 'Constitutional',
    keywords: ['triple talaq', 'Muslim women', 'arbitrary', 'divorce', 'personal law', 'Article 14']
  },
  {
    caseName: 'Navtej Singh Johar v. Union of India',
    citation: '(2018) 10 SCC 1',
    court: 'Supreme Court',
    year: 2018,
    judges: ['Misra CJ', 'Nariman J', 'Chandrachud J', 'Malhotra J', 'Khanwilkar J'],
    summary: 'Challenge to Section 377 IPC which criminalized consensual homosexual acts between adults.',
    legalPrinciple: 'Consensual sexual acts between adults in private cannot be criminalized. Section 377 insofar as it criminalizes consensual homosexual acts violates Articles 14, 15, 19, and 21.',
    verdict: 'Unanimously struck down Section 377 IPC to the extent it criminalizes consensual homosexual acts between adults. Overruled Suresh Kumar Koushal v. Naz Foundation (2013).',
    significance: 'Decriminalized homosexuality in India. A landmark for LGBTQ+ rights and personal liberty.',
    relatedSections: ['Section 377 IPC', 'Article 14', 'Article 15', 'Article 19', 'Article 21'],
    relatedActs: ['Indian Penal Code, 1860', 'Constitution of India'],
    category: 'Constitutional',
    keywords: ['Section 377', 'homosexuality', 'LGBTQ', 'decriminalization', 'privacy', 'dignity']
  },
  {
    caseName: 'Joseph Shine v. Union of India',
    citation: '(2019) 3 SCC 39',
    court: 'Supreme Court',
    year: 2018,
    judges: ['Misra CJ', 'Nariman J', 'Chandrachud J', 'Malhotra J', 'Khanwilkar J'],
    summary: 'Challenge to Section 497 IPC which made adultery a criminal offence but only punished the man, not the woman.',
    legalPrinciple: 'Section 497 IPC treats a married woman as chattel of her husband and is based on patriarchal notions. Adultery can be a ground for civil consequences (divorce) but not criminal prosecution.',
    verdict: 'Struck down Section 497 IPC (adultery) as unconstitutional for being arbitrary and discriminatory. Adultery remains a ground for divorce but is no longer a crime.',
    significance: 'Ended the colonial-era notion that wife is husband\'s property. Adultery is now only a civil wrong, not a criminal offence.',
    relatedSections: ['Section 497 IPC', 'Article 14', 'Article 15', 'Article 21'],
    relatedActs: ['Indian Penal Code, 1860', 'Constitution of India'],
    category: 'Constitutional',
    keywords: ['adultery', 'Section 497', 'decriminalization', 'gender equality', 'marriage']
  },
  {
    caseName: 'Indian Young Lawyers Association v. State of Kerala (Sabarimala)',
    citation: '(2019) 11 SCC 1',
    court: 'Supreme Court',
    year: 2018,
    judges: ['Misra CJ', 'Nariman J', 'Chandrachud J', 'Malhotra J', 'Khanwilkar J'],
    summary: 'Challenged the ban on entry of women of menstruating age (10-50) into the Sabarimala temple in Kerala.',
    legalPrinciple: 'The exclusion of women from a public temple constitutes discrimination. Devotion cannot be subjected to gender discrimination. Article 25(1) guarantees freedom of religion to all persons equally.',
    verdict: 'By 4:1, the Court struck down the ban as violating Articles 14, 15, 25, and 26. Justice Malhotra dissented. A 9-judge bench was later constituted to reconsider.',
    significance: 'Major case on gender equality vs. religious practice. Referred to a larger bench on broader questions of essential religious practices.',
    relatedSections: ['Article 14', 'Article 15', 'Article 25', 'Article 26'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['Sabarimala', 'women entry', 'temple', 'religious practice', 'gender equality', 'menstruation']
  },
  {
    caseName: 'Common Cause v. Union of India (Living Will)',
    citation: '(2018) 5 SCC 1',
    court: 'Supreme Court',
    year: 2018,
    judges: ['Misra CJ', 'Khanwilkar J', 'Chandrachud J', 'Sikri J', 'Bhushan J'],
    summary: 'PIL seeking recognition of living wills and advance medical directives for passive euthanasia.',
    legalPrinciple: 'Right to die with dignity is a fundamental right under Article 21. An individual can execute an advance medical directive (living will) refusing life-prolonging treatment.',
    verdict: 'Recognized the right to execute an advance directive (living will). Laid down detailed guidelines for passive euthanasia and living wills, including safeguards with medical boards and High Court permission.',
    significance: 'Expanded Aruna Shanbaug by allowing advance directives. Gave legal framework for end-of-life decisions.',
    relatedSections: ['Article 21'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['living will', 'advance directive', 'euthanasia', 'right to die', 'dignity', 'Article 21']
  },
  {
    caseName: 'Bandhua Mukti Morcha v. Union of India',
    citation: 'AIR 1984 SC 802',
    court: 'Supreme Court',
    year: 1984,
    judges: ['Bhagwati J', 'Pathak J', 'Amarendra Nath Sen J'],
    summary: 'PIL brought by an NGO about bonded labourers working in stone quarries in Haryana under inhuman conditions.',
    legalPrinciple: 'Article 21 includes the right to live with human dignity, free from exploitation. The state has an obligation to identify, release, and rehabilitate bonded labourers.',
    verdict: 'Directed the state to identify and release all bonded labourers, provide rehabilitation, and ensure the Bonded Labour System (Abolition) Act is effectively implemented.',
    significance: 'Expanded PIL and Article 21 to include protection from exploitation. Directed state machinery to act on bonded labour.',
    relatedSections: ['Article 21', 'Article 23', 'Article 24'],
    relatedActs: ['Constitution of India', 'Bonded Labour System (Abolition) Act, 1976'],
    category: 'Constitutional',
    keywords: ['bonded labour', 'exploitation', 'rehabilitation', 'dignity', 'PIL', 'Article 23']
  },
  {
    caseName: 'Waman Rao v. Union of India',
    citation: 'AIR 1981 SC 271',
    court: 'Supreme Court',
    year: 1981,
    judges: ['Chandrachud CJ', 'Bhagwati J', 'Gupta J', 'Tulzapurkar J', 'Varadarajan J'],
    summary: 'Challenge to the constitutional validity of certain Maharashtra land reform laws placed in the 9th Schedule.',
    legalPrinciple: 'The basic structure doctrine applies to amendments made after 24.4.1973 (date of Kesavananda). Laws placed in the 9th Schedule before this date are immune from challenge.',
    verdict: 'Amendments to the 9th Schedule made after 24.4.1973 can be challenged if they damage the basic structure. Confirmed the cutoff date.',
    significance: 'Set the Kesavananda date (24.4.1973) as the dividing line for 9th Schedule immunity. Later applied in I.R. Coelho.',
    relatedSections: ['Article 31B', 'Ninth Schedule', 'Article 368'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['ninth schedule', 'basic structure', '1973 cutoff', 'land reform']
  },
  {
    caseName: 'T.M.A. Pai Foundation v. State of Karnataka',
    citation: '(2002) 8 SCC 481',
    court: 'Supreme Court',
    year: 2002,
    judges: ['Kirpal CJ', 'Khare J', 'Variava J', 'Bhan J', 'Arijit Pasayat J', 'Ruma Pal J', 'Sema J', 'Quadri J', 'Dharmadhikari J', 'Hegde J', 'Sinha J'],
    summary: 'Whether minority educational institutions can be regulated and whether they have to admit non-minority students.',
    legalPrinciple: 'Minority institutions have the right to establish and administer educational institutions. Reasonable regulations regarding standards are permissible but not regulations that destroy minority character.',
    verdict: 'Both linguistic and religious minorities have the right under Article 30. State can impose reasonable regulations. Capitation fee can be regulated but reasonable surplus is allowed.',
    significance: 'Settled the law on minority educational institutions. 11-judge bench decision that balanced minority rights with regulatory framework.',
    relatedSections: ['Article 19(1)(g)', 'Article 26', 'Article 29', 'Article 30'],
    relatedActs: ['Constitution of India'],
    category: 'Constitutional',
    keywords: ['minority institutions', 'education', 'Article 30', 'regulation', 'capitation fee']
  },
  {
    caseName: 'Supriyo v. Union of India (Same-Sex Marriage)',
    citation: '2023 INSC 920',
    court: 'Supreme Court',
    year: 2023,
    judges: ['Chandrachud CJI', 'Kaul J', 'Ravikumar J', 'Kohli J', 'Narasimha J'],
    summary: 'Petitions seeking legal recognition of same-sex marriages under the Special Marriage Act.',
    legalPrinciple: 'While the Constitution does not discriminate based on sexual orientation, the right to marry is not a fundamental right. The legislature must address the issue of same-sex marriage.',
    verdict: 'The Court declined to legalize same-sex marriage but recognized the right of queer couples to certain legal protections. Directed the government to form a committee to examine rights of queer couples.',
    significance: 'While not granting marriage rights, acknowledged the existence and dignity of same-sex relationships. Left the question for Parliament.',
    relatedSections: ['Article 14', 'Article 15', 'Article 19', 'Article 21'],
    relatedActs: ['Constitution of India', 'Special Marriage Act, 1954'],
    category: 'Constitutional',
    keywords: ['same-sex marriage', 'LGBTQ', 'Special Marriage Act', 'queer rights', 'marriage equality']
  },
  {
    caseName: 'K.S. Puttaswamy v. Union of India (Aadhaar)',
    citation: '(2019) 1 SCC 1',
    court: 'Supreme Court',
    year: 2019,
    judges: ['Sikri J', 'Bhushan J', 'Nazeer J', 'Chandrachud J', 'Ashok Bhushan J'],
    summary: 'Challenge to the constitutional validity of the Aadhaar Act and whether mandatory Aadhaar violates the right to privacy.',
    legalPrinciple: 'Aadhaar is constitutionally valid for delivery of subsidies and tax filing but cannot be mandated for bank accounts, mobile phones, or school admissions. Proportionality test applies to privacy restrictions.',
    verdict: 'By 4:1, upheld Aadhaar for government subsidies and IT returns. Struck down Section 57 (private use of Aadhaar). Justice Chandrachud dissented, calling the Act unconstitutional.',
    significance: 'Applied proportionality test to privacy. Restricted Aadhaar\'s scope while upholding its core purpose for government services.',
    relatedSections: ['Article 21', 'Article 14', 'Article 19'],
    relatedActs: ['Constitution of India', 'Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016'],
    category: 'Constitutional',
    keywords: ['Aadhaar', 'privacy', 'biometric', 'proportionality', 'surveillance', 'subsidies']
  },
  {
    caseName: 'Election Commission of India v. Jan Chaukidar (Electoral Bonds)',
    citation: '2024 INSC 90',
    court: 'Supreme Court',
    year: 2024,
    judges: ['Chandrachud CJI', 'Pardiwala J', 'Sanjiv Khanna J', 'Dipankar Datta J', 'Manoj Misra J'],
    summary: 'Challenge to the electoral bonds scheme that allowed anonymous donations to political parties.',
    legalPrinciple: 'Voters\' right to information about political funding is a fundamental right under Article 19(1)(a). Anonymous electoral bonds violate the right to information.',
    verdict: 'Unanimously struck down the Electoral Bonds Scheme as unconstitutional. Directed the SBI to disclose all bond purchase details to the Election Commission.',
    significance: 'Major blow to opaque political funding. Upheld transparency in electoral democracy as a constitutional requirement.',
    relatedSections: ['Article 19(1)(a)', 'Article 14'],
    relatedActs: ['Constitution of India', 'Finance Act, 2017'],
    category: 'Constitutional',
    keywords: ['electoral bonds', 'political funding', 'transparency', 'right to information', 'elections']
  }
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');
    const deleted = await CourtVerdict.deleteMany({ category: 'Constitutional' });
    if (deleted.deletedCount > 0) console.log(`Cleared ${deleted.deletedCount} existing constitutional verdicts`);
    for (let i = 0; i < verdicts.length; i++) {
      await CourtVerdict.create(verdicts[i]);
      console.log(`[${i + 1}/${verdicts.length}] ${verdicts[i].caseName} (${verdicts[i].year})`);
    }
    console.log(`Done: seeded ${verdicts.length} constitutional verdicts`);
    await mongoose.disconnect();
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}
seed();
